In [15]:
import pandas as pd
import numpy as np
from numpy.random import randn

###Series

In [2]:
labels = ['a', 'b', 'c']
minha_lista = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(data = labels, index = minha_lista)

10    a
20    b
30    c
dtype: object

In [5]:
pd.Series(labels, minha_lista)

10    a
20    b
30    c
dtype: object

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
ser1 = pd.Series([1,2,3,4], index = ['EUA', 'Alemanha', 'Russia', 'Japão'])
ser1

EUA         1
Alemanha    2
Russia      3
Japão       4
dtype: int64

In [9]:
ser2 = pd.Series([1,2,5,4], index = ['EUA', 'Alemanha', 'Italia', 'Japão'])
ser2

EUA         1
Alemanha    2
Italia      5
Japão       4
dtype: int64

In [10]:
ser1['EUA']

np.int64(1)

In [11]:
ser1['Alemanha']

np.int64(2)

In [12]:
ser1[['Alemanha', 'Russia']]

Alemanha    2
Russia      3
dtype: int64

In [13]:
ser1 + ser2

Alemanha    4.0
EUA         2.0
Italia      NaN
Japão       8.0
Russia      NaN
dtype: float64

###DataFrame

In [16]:
df = pd.DataFrame(randn(5,4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A  0.871098 -0.665590 -1.926392 -1.618328
B  0.531324 -0.202678 -0.764131  0.322598
C  0.766405  1.167030  0.392177  2.574728
D  0.091734 -0.205567  0.633671  2.270462
E  0.016833 -0.184039 -0.512652 -0.452594

In [17]:
df['W']

A    0.871098
B    0.531324
C    0.766405
D    0.091734
E    0.016833
Name: W, dtype: float64

In [18]:
df[['W', 'X']]

          W         X
A  0.871098 -0.665590
B  0.531324 -0.202678
C  0.766405  1.167030
D  0.091734 -0.205567
E  0.016833 -0.184039

In [19]:
df[['W']]

          W
A  0.871098
B  0.531324
C  0.766405
D  0.091734
E  0.016833

In [20]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  0.871098 -0.665590 -1.926392 -1.618328 -1.055294
B  0.531324 -0.202678 -0.764131  0.322598 -0.232807
C  0.766405  1.167030  0.392177  2.574728  1.158583
D  0.091734 -0.205567  0.633671  2.270462  0.725405
E  0.016833 -0.184039 -0.512652 -0.452594 -0.495819

In [21]:
del df['new'] #ou df.drop('new', axis = 1) 1-> colunas e 0-> linhas
df

          W         X         Y         Z
A  0.871098 -0.665590 -1.926392 -1.618328
B  0.531324 -0.202678 -0.764131  0.322598
C  0.766405  1.167030  0.392177  2.574728
D  0.091734 -0.205567  0.633671  2.270462
E  0.016833 -0.184039 -0.512652 -0.452594

In [22]:
df

          W         X         Y         Z
A  0.871098 -0.665590 -1.926392 -1.618328
B  0.531324 -0.202678 -0.764131  0.322598
C  0.766405  1.167030  0.392177  2.574728
D  0.091734 -0.205567  0.633671  2.270462
E  0.016833 -0.184039 -0.512652 -0.452594

In [23]:
df.loc['A']

W    0.871098
X   -0.665590
Y   -1.926392
Z   -1.618328
Name: A, dtype: float64

In [24]:
df.loc[['A', 'B']]

          W         X         Y         Z
A  0.871098 -0.665590 -1.926392 -1.618328
B  0.531324 -0.202678 -0.764131  0.322598

In [25]:
df.iloc[0,2]

np.float64(-1.926392129371847)