In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn

###iloc e filtros

In [24]:
df = pd.DataFrame(randn(5,4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A -0.612610 -0.891929  0.737243 -0.048359
B -1.490728 -0.457706  1.175521  1.122740
C  0.659543 -0.139012 -0.329176 -3.359584
D -1.867315  0.909677 -0.346163 -0.437328
E  1.965925  0.324521 -0.514014  0.782265

In [3]:
df.loc[['A', 'B'], ['W']] #df.loc[[linas], [colunas]]

          W
A -0.831372
B  0.630400

In [4]:
df.iloc[:-1, 1:]

          X         Y         Z
A  0.780175 -1.558022  1.747009
B  0.520423  0.270541 -0.853713
C  0.326395 -1.960027  0.463300
D -0.787614 -1.763595 -0.266915

In [5]:
df.iloc[:-1, 1:4] #[incluso:excluso]

          X         Y         Z
A  0.780175 -1.558022  1.747009
B  0.520423  0.270541 -0.853713
C  0.326395 -1.960027  0.463300
D -0.787614 -1.763595 -0.266915

In [6]:
df > 0

       W      X      Y      Z
A  False   True  False   True
B   True   True   True  False
C   True   True  False   True
D  False  False  False  False
E   True  False  False   True

In [7]:
df[df> 0]

          W         X         Y         Z
A       NaN  0.780175       NaN  1.747009
B  0.630400  0.520423  0.270541       NaN
C  0.720209  0.326395       NaN  0.463300
D       NaN       NaN       NaN       NaN
E  0.249056       NaN       NaN  0.324708

In [8]:
df['Y'] > 0

A    False
B     True
C    False
D    False
E    False
Name: Y, dtype: bool

In [9]:
df[df['Y'] > 0]

        W         X         Y         Z
B  0.6304  0.520423  0.270541 -0.853713

In [10]:
df[(df['Y'] > 0) & (df['X'] > 0)]

        W         X         Y         Z
B  0.6304  0.520423  0.270541 -0.853713

###Operações com índices

In [25]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [26]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [27]:
df.reset_index() #mostra uma cópia. Para ser real teria que colocar o inplace=True

  index         W         X         Y         Z
0     A -0.612610 -0.891929  0.737243 -0.048359
1     B -1.490728 -0.457706  1.175521  1.122740
2     C  0.659543 -0.139012 -0.329176 -3.359584
3     D -1.867315  0.909677 -0.346163 -0.437328
4     E  1.965925  0.324521 -0.514014  0.782265

In [18]:
#Para voltar ao que era é só escrever df.set_index('index', inplace=True)

In [28]:
df

          W         X         Y         Z
A -0.612610 -0.891929  0.737243 -0.048359
B -1.490728 -0.457706  1.175521  1.122740
C  0.659543 -0.139012 -0.329176 -3.359584
D -1.867315  0.909677 -0.346163 -0.437328
E  1.965925  0.324521 -0.514014  0.782265

In [33]:
novo_ind = 'CA NY WY OR CO'.split()
novo_ind

['CA', 'NY', 'WY', 'OR', 'CO']

In [36]:
df['novo_index'] = novo_ind
#df.set_index('novo_index') com esse comando o Pandas retira a coluna de index antiga e coloca a nova
df.reset_index().set_index('novo_index')

           index         W         X         Y         Z
novo_index
CA             A -0.612610 -0.891929  0.737243 -0.048359
NY             B -1.490728 -0.457706  1.175521  1.122740
WY             C  0.659543 -0.139012 -0.329176 -3.359584
OR             D -1.867315  0.909677 -0.346163 -0.437328
CO             E  1.965925  0.324521 -0.514014  0.782265