In [2]:
import pandas as pd
import numpy as np
from numpy.random import randn

###iloc e filtros

In [3]:
df = pd.DataFrame(randn(5,4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A -0.955740  1.964790 -0.288369  1.347056
B  0.304216  1.653640 -0.558124  2.853020
C -1.206080  0.284253 -0.488750 -0.618945
D -0.480900  0.412302  1.192083  1.710456
E -0.107498  0.942452 -0.382763  0.601113

In [ ]:
df.loc[['A', 'B'], ['W']] #df.loc[[linas], [colunas]]

          W
A -0.955740
B  0.304216

In [6]:
df.iloc[:-1, 1:]

          X         Y         Z
A  1.964790 -0.288369  1.347056
B  1.653640 -0.558124  2.853020
C  0.284253 -0.488750 -0.618945
D  0.412302  1.192083  1.710456

In [7]:
df.iloc[:-1, 1:4] #[incluso:excluso]

          X         Y         Z
A  1.964790 -0.288369  1.347056
B  1.653640 -0.558124  2.853020
C  0.284253 -0.488750 -0.618945
D  0.412302  1.192083  1.710456

In [8]:
df > 0

       W     X      Y      Z
A  False  True  False   True
B   True  True  False   True
C  False  True  False  False
D  False  True   True   True
E  False  True  False   True

In [9]:
df[df> 0]

          W         X         Y         Z
A       NaN  1.964790       NaN  1.347056
B  0.304216  1.653640       NaN  2.853020
C       NaN  0.284253       NaN       NaN
D       NaN  0.412302  1.192083  1.710456
E       NaN  0.942452       NaN  0.601113

In [10]:
df['Y'] > 0

A    False
B    False
C    False
D     True
E    False
Name: Y, dtype: bool

In [11]:
df[df['Y'] > 0]

        W         X         Y         Z
D -0.4809  0.412302  1.192083  1.710456

In [13]:
df[(df['Y'] > 0) & (df['X'] > 0)]

        W         X         Y         Z
D -0.4809  0.412302  1.192083  1.710456

###Operações com índices