In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn

###iloc e filtros

In [2]:
df = pd.DataFrame(randn(5,4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A -0.314913  0.602280 -1.010903  0.462778
B  1.699415  0.139542  1.000556  0.957494
C  0.378432 -0.386527  0.248565  0.535332
D  0.329257 -1.751821  0.948934 -1.403029
E -1.072943 -0.867668  2.626043 -1.756235

In [3]:
df.loc[['A', 'B'], ['W']] #df.loc[[linas], [colunas]]

          W
A -0.314913
B  1.699415

In [4]:
df.iloc[:-1, 1:]

          X         Y         Z
A  0.602280 -1.010903  0.462778
B  0.139542  1.000556  0.957494
C -0.386527  0.248565  0.535332
D -1.751821  0.948934 -1.403029

In [5]:
df.iloc[:-1, 1:4] #[incluso:excluso]

          X         Y         Z
A  0.602280 -1.010903  0.462778
B  0.139542  1.000556  0.957494
C -0.386527  0.248565  0.535332
D -1.751821  0.948934 -1.403029

In [6]:
df > 0

       W      X      Y      Z
A  False   True  False   True
B   True   True   True   True
C   True  False   True   True
D   True  False   True  False
E  False  False   True  False

In [7]:
df[df> 0]

          W         X         Y         Z
A       NaN  0.602280       NaN  0.462778
B  1.699415  0.139542  1.000556  0.957494
C  0.378432       NaN  0.248565  0.535332
D  0.329257       NaN  0.948934       NaN
E       NaN       NaN  2.626043       NaN

In [8]:
df['Y'] > 0

A    False
B     True
C     True
D     True
E     True
Name: Y, dtype: bool

In [9]:
df[df['Y'] > 0]

          W         X         Y         Z
B  1.699415  0.139542  1.000556  0.957494
C  0.378432 -0.386527  0.248565  0.535332
D  0.329257 -1.751821  0.948934 -1.403029
E -1.072943 -0.867668  2.626043 -1.756235

In [10]:
df[(df['Y'] > 0) & (df['X'] > 0)]

          W         X         Y         Z
B  1.699415  0.139542  1.000556  0.957494

###Operações com índices

In [11]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [12]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [13]:
df.reset_index() #mostra uma cópia. Para ser real teria que colocar o inplace=True

  index         W         X         Y         Z
0     A -0.314913  0.602280 -1.010903  0.462778
1     B  1.699415  0.139542  1.000556  0.957494
2     C  0.378432 -0.386527  0.248565  0.535332
3     D  0.329257 -1.751821  0.948934 -1.403029
4     E -1.072943 -0.867668  2.626043 -1.756235

In [14]:
#Para voltar ao que era é só escrever df.set_index('index', inplace=True)

In [15]:
df

          W         X         Y         Z
A -0.314913  0.602280 -1.010903  0.462778
B  1.699415  0.139542  1.000556  0.957494
C  0.378432 -0.386527  0.248565  0.535332
D  0.329257 -1.751821  0.948934 -1.403029
E -1.072943 -0.867668  2.626043 -1.756235

In [16]:
novo_ind = 'CA NY WY OR CO'.split()
novo_ind

['CA', 'NY', 'WY', 'OR', 'CO']

In [17]:
df['novo_index'] = novo_ind
#df.set_index('novo_index') com esse comando o Pandas retira a coluna de index antiga e coloca a nova
df.reset_index().set_index('novo_index')

           index         W         X         Y         Z
novo_index
CA             A -0.314913  0.602280 -1.010903  0.462778
NY             B  1.699415  0.139542  1.000556  0.957494
WY             C  0.378432 -0.386527  0.248565  0.535332
OR             D  0.329257 -1.751821  0.948934 -1.403029
CO             E -1.072943 -0.867668  2.626043 -1.756235

###Hierarquia de índices e índices múltiplos

In [30]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [31]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [32]:
df = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns=['A', 'B'])
df

             A         B
G1 1 -0.700149 -0.792172
   2 -0.378115 -1.208144
   3 -0.330903  0.150063
G2 1 -1.129800 -1.726814
   2  1.812672  0.771857
   3 -0.188332  1.228213

In [33]:
df.loc['G1']

          A         B
1 -0.700149 -0.792172
2 -0.378115 -1.208144
3 -0.330903  0.150063

In [34]:
df.loc['G1'].loc[1]

A   -0.700149
B   -0.792172
Name: 1, dtype: float64

In [35]:
df.index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [36]:
df.index.names

FrozenList([None, None])

In [37]:
df.index.names = ['Grupo', 'Número']
df

                     A         B
Grupo Número
G1    1      -0.700149 -0.792172
      2      -0.378115 -1.208144
      3      -0.330903  0.150063
G2    1      -1.129800 -1.726814
      2       1.812672  0.771857
      3      -0.188332  1.228213

In [38]:
df.xs('G1')

               A         B
Número
1      -0.700149 -0.792172
2      -0.378115 -1.208144
3      -0.330903  0.150063

In [40]:
df.xs(1, level='Número')

              A         B
Grupo
G1    -0.700149 -0.792172
G2    -1.129800 -1.726814

###Manipulação de dados ausentes

In [41]:
df = pd.DataFrame({
    'A': [1,2,np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1,2,3]
})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [44]:
df.dropna(axis = 0)

     A    B  C
0  1.0  5.0  1

In [45]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [46]:
df.dropna(axis = 1, thresh=2)

     A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [47]:
df.fillna(0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [48]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [49]:
df.ffill()

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [50]:
df.bfill()

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

###Groupby

In [60]:
data = {
    'Classe': ['Júnior', 'Júnior', 'Pleno', 'Pleno', 'Sênior', 'Sênior'],
    'Nome': ['Jorge', 'Carlos', 'Roberta', 'Patrícia', 'Bruno', 'Vera'],
    'Venda': [200, 120, 340, 124, 243, 350]
}

df = pd.DataFrame(data)
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [61]:
group = df.groupby('Classe')
group.sum()

                   Nome  Venda
Classe
Júnior      JorgeCarlos    320
Pleno   RobertaPatrícia    464
Sênior        BrunoVera    593

In [62]:
df.groupby('Classe').min()

            Nome  Venda
Classe
Júnior    Carlos    120
Pleno   Patrícia    124
Sênior     Bruno    243

In [64]:
df.groupby('Classe').max()

           Nome  Venda
Classe
Júnior    Jorge    200
Pleno   Roberta    340
Sênior     Vera    350

In [65]:
df2 = df.copy()

In [67]:
df2

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [68]:
df2['Venda'] = [150, 432, 190, 230, 410, 155]

In [69]:
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [70]:
df2

   Classe      Nome  Venda
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [71]:
df3 = pd.concat([df, df2])
df3

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [72]:
df3.groupby(['Classe', 'Nome']).sum()

                 Venda
Classe Nome
Júnior Carlos      552
       Jorge       350
Pleno  Patrícia    354
       Roberta     530
Sênior Bruno       653
       Vera        505