In [1]:
import pandas as pd
import numpy as np

###Merge, concat e join

In [2]:
df1 = pd.DataFrame({'A': ['A0', 'A1','A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0,1,2,3])

df2 = pd.DataFrame({'A': ['A4', 'A5','A6', 'A7'],
'B': ['B4', 'B5', 'B6', 'B7'],
'C': ['C4', 'C5', 'C6', 'C7'],
'D': ['D4', 'D5', 'D6', 'D7']},
index=[4,5,6,7])

df3 = pd.DataFrame({'A': ['A8', 'A9','A10', 'A11'],
'B': ['B8', 'B9', 'B10', 'B11'],
'C': ['C8', 'C9', 'C10', 'C11'],
'D': ['D8', 'D9', 'D10', 'D11']},
index=[8,9,10,11])

In [3]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [4]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [5]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [6]:
pd.concat([df1, df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [7]:
pd.concat([df1, df2, df3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [8]:
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})

direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})

In [9]:
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [10]:
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [11]:
pd.merge(esquerda, direita)

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [12]:
pd.merge(esquerda, direita, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [13]:
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
'key2': ['K0', 'K1', 'K0', 'K1'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})

direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
'key2': ['K0', 'K0', 'K0', 'K0'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})

In [14]:
esquerda

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [15]:
direita

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [16]:
pd.merge(esquerda, direita, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [17]:
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [18]:
esquerda = pd.DataFrame({'A': ['A0', 'A1','A2'],
'B': ['B0', 'B1', 'B2']},
index=['K0', 'K1', 'K2'])

direita = pd.DataFrame({'C': ['C0', 'C2','C3'],
'D': ['D0', 'D2', 'D3']},
index=['K0', 'K2', 'K3'])

In [19]:
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [20]:
direita

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [21]:
esquerda.join(direita)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [22]:
esquerda.join(direita, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

###Operações no Pandas

In [23]:
df = pd.DataFrame({'col1': [1,2,3,4], 'col2':[444, 555, 666, 444], 'col3':['abc', 'def','ghi', 'xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [25]:
df.memory_usage()

Index    132
col1      32
col2      32
col3      32
dtype: int64

###informações sobre valores exclusivos

In [26]:
df['col2'].unique()

array([444, 555, 666])

In [27]:
df['col2'].nunique()

3

In [28]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

###Aplicando funções

In [29]:
def comp(x):
    return x ** 2 + 3

In [30]:
df['col1'].apply(comp)

0     4
1     7
2    12
3    19
Name: col1, dtype: int64

In [31]:
df['col4'] = df['col1'].apply(lambda x: x ** 2 + 3)
df

   col1  col2 col3  col4
0     1   444  abc     4
1     2   555  def     7
2     3   666  ghi    12
3     4   444  xyz    19

In [32]:
df['col1'].sum()

np.int64(10)

In [33]:
df['col1'].mean()

np.float64(2.5)

In [34]:
df['col1'].product()

np.int64(24)

In [35]:
df['col1'].std()

1.2909944487358056

In [36]:
df['col1'].max()

4

In [37]:
df['col1'].min()

1

In [38]:
df['col1'].idxmax()

3

In [39]:
df[df['col2'] == 444]['col1'].sum()

np.int64(5)

In [40]:
df.sort_values(by='col2')

   col1  col2 col3  col4
0     1   444  abc     4
3     4   444  xyz    19
1     2   555  def     7
2     3   666  ghi    12

In [41]:
data = {'A':['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
'B':['one', 'one', 'two', 'two', 'one', 'one'],
'C': ['x', 'y', 'x', 'y', 'x', 'y'],
'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [42]:
dict_map = {'one': '1', 'two': '2'}
df['E'] = df['B'].map(dict_map)
df

     A    B  C  D  E
0  foo  one  x  1  1
1  foo  one  y  3  1
2  foo  two  x  2  2
3  bar  two  y  5  2
4  bar  one  x  4  1
5  bar  one  y  1  1

In [43]:
df.pivot_table(index='A',columns='B', values='D')

B    one  two
A
bar  2.5  5.0
foo  2.0  2.0

###Dados temporais

In [44]:
numero_de_dias = 100
datas = pd.date_range(start='1/1/2021', periods=numero_de_dias)
df = pd.DataFrame(range(numero_de_dias), columns=['number'], index=datas)
df

            number
2021-01-01       0
2021-01-02       1
2021-01-03       2
2021-01-04       3
2021-01-05       4
...            ...
2021-04-06      95
2021-04-07      96
2021-04-08      97
2021-04-09      98
2021-04-10      99

[100 rows x 1 columns]

In [45]:
df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
               '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05',
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21',
               '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25',
               '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29',
               '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02',
               '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06',
               '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10'],
              dtype='datetime64[ns]', freq='D')

In [46]:
df.index[0]

Timestamp('2021-01-01 00:00:00')

In [47]:
df.index[0].day

1

In [48]:
df.index[0].month

1

In [49]:
df.index[0].year

2021

In [50]:
df.index[0].hour

0

In [52]:
df[df.index.day == 10]

            number
2021-01-10       9
2021-02-10      40
2021-03-10      68
2021-04-10      99

In [53]:
df['Month'] = df.index.month
df

            number  Month
2021-01-01       0      1
2021-01-02       1      1
2021-01-03       2      1
2021-01-04       3      1
2021-01-05       4      1
...            ...    ...
2021-04-06      95      4
2021-04-07      96      4
2021-04-08      97      4
2021-04-09      98      4
2021-04-10      99      4

[100 rows x 2 columns]

In [54]:
import datetime

In [55]:
df[df.index > datetime.datetime(2021, 1, 10)]

            number  Month
2021-01-11      10      1
2021-01-12      11      1
2021-01-13      12      1
2021-01-14      13      1
2021-01-15      14      1
...            ...    ...
2021-04-06      95      4
2021-04-07      96      4
2021-04-08      97      4
2021-04-09      98      4
2021-04-10      99      4

[90 rows x 2 columns]

###Entrada e saída de dados

In [58]:
df1 = pd.read_csv('exemplo.csv', sep=',', decimal='.')
df1

          0         1         2         3
0 -0.394813 -0.694630  0.253393  0.602590
1 -2.134217  1.141381 -0.130142  0.690936
2 -0.223754  0.365133 -0.104233 -0.182788
3  0.108066  0.331332  0.053708 -0.280468
4  0.085290  0.740834 -0.596941  0.243950

In [59]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      float64
 1   1       5 non-null      float64
 2   2       5 non-null      float64
 3   3       5 non-null      float64
dtypes: float64(4)
memory usage: 292.0 bytes

In [60]:
df1.to_csv('exmplo2.csv', sep=';', decimal=',')